name: buffer-analyze # Override to be the name of the application
track: stable # stable | canary
replicaCount: 3
image:
  repository: bufferapp/buffer-analyze # Override with the docker image
  tag: latest # this will be overriden by the build process
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 150Mi
  requests:
    cpu: 100m
    memory: 50Mi
extraMainContainerValues:
  livenessProbe:
    httpGet:
      path: /health-check
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 5
    failureThreshold: 2
    timeoutSeconds: 1
extraSpecSpecs:
  dnsPolicy: ClusterFirst
  terminationGracePeriodSeconds: 30
  restartPolicy: Always
extraSpecs:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 10
env:
  - name: API_ADDR
    value: https://api.bufferapp.com
  - name: ANALYZE_API_ADDR
    value: https://analyze-api.buffer.com
  - name: BUGSNAG_KEY
    valueFrom:
      secretKeyRef:
        key: bugsnag
        name: buffer-analyze-keys
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        key: aws-access-key-id
        name: buffer-analyze-keys
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: aws-secret-access-key
        name: buffer-analyze-keys
healthcheck: # checkout https://github.com/bufferapp/EKG for complete docs
  enabled: false
  config:
    port: 8086
    livenessChecks:
    - name: httpget-check
      type: httpGetCheck
      url: http://localhost:3000
    readinessChecks:
    - name: httpget-check
      type: httpGetCheck
      url: http://localhost:3000
# enable the ingress open up the service to the public internet
service:
  enabled: true
  externalPort: 80
  externalTLSPort: 443
  internalPort: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:980620087509:certificate/6b704a93-67de-444c-89fc-9f659bf2dd42
ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
  serviceDevUrl: "analyze.dev.buffer.com"
